FROM nginx:latest

RUN rm /etc/nginx/nginx.conf

COPY ./default.conf /etc/nginx/nginx.conf

#RUN mkdir -p /etc/nginx/ssl

#COPY ./metafalica/certificate.crt /etc/nginx/ssl/certificate.crt
#COPY ./metafalica/private.key /etc/nginx/ssl/private.key
